### ISSUE TITLE
Fails with Cygwin Perl 5.14.2 due to unavailable is_core().

### ISSUE THREAD

**Issue by vadz** [perlancar/perl-App-fatten#4]
Any attempt to use fails with

```
ERROR 500: Died: Undefined subroutine &Module::CoreList::is_core called at <...>/lib/perl5/App/tracepm.pm line 164, <$fh> line 1.
```

AFAICS `is_core` is new in 5.20. If the script can't avoid using it, it should at least clearly state that it requires 5.20.

**Comment by perlancar** [comment]
Closing this issue as it has been fixed.
